version: '3.8'

services:
  app:
    build:
      context: ./fast_api_app
    ports:
      - "8945:8945"
    depends_on:
      - redis

  redis:
    environment:
      - REDIS_PASSWORD=123421
    image: "redis:latest"
    ports:
      - "6379:6379"